sudo: required
services:
  - docker

before_install:
  - docker build -t npbeard/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true npbeard/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: 
  on:
    branch: master